[build]
  base = "frontend"
  publish = ".next"
  command = "cd .. && npm install && npm run build"

[functions]
  directory = "../functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
